### ISSUE TITLE
Release on different repositories

### ISSUE THREAD

**Issue by arouel** [mdedetrich/utforsca#1]
Thank you very much for sharing this utility library. I'm also maintaining an implementation to resolve case objects of sealed traits. I would reuse your solution as managed dependency but your artifactory repository is a bit slow on my end. I would appreciate if it is published at The Central Repository or Bintray.

**Comment by mdedetrich** [comment]
Sorry for the late response, will look into it, is artifactory still slow?

**Comment by mdedetrich** [comment]
Finally got sonatype working, so its not published on Sonatype
